OData/AspNetCoreOData

src/Microsoft.AspNetCore.OData/Extensions/ActionModelExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Routing/Conventions/AttributeRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/SingletonRoutingConvention.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Related to issue #34.
It seems we can’t hit the Authorize because the new added "SelectorModel" doesn't have the attributes added.
In the debug endpoint, there’s no “AuthorizeAttribute” in the metadata of Endpoint
However,  for “Get” method, the metadata of Endpoint has the “AuthrozeAttribute” as below:
This PR is to fix this problem.

fix issue #34, add the attributes to new selector model

---

.gitconfig
src/Microsoft.AspNetCore.OData/Edm/ClrTypeCache.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultODataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultTests.cs
test/Microsoft.AspNetCore.OData.Tests/ODataOptionsTests.cs

Porting https://github.com/OData/WebApi/pull/2362 to v8 repo

EnableQuery should perform checks before controller execution

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ConcurrentQuery/ConcurrentQueryController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ConcurrentQuery/ConcurrentQueryEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ConcurrentQuery/ConcurrentQueryODataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ConcurrentQuery/ConcurrentQueryTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/QueryValidationBeforeAction/QueryValidationBeforeActionController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/QueryValidationBeforeAction/QueryValidationBeforeActionEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/QueryValidationBeforeAction/QueryValidationBeforeActionODataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/QueryValidationBeforeAction/QueryValidationBeforeActionTests.cs

Porting https://github.com/OData/WebApi/pull/2397 to v8 repo

Storing request query information on HttpContext

---

sample/ODataDynamicModel/Extensions/EntitySetWithKeyTemplateSegment.cs
sample/ODataDynamicModel/Extensions/MyODataRoutingApplicationModelProvider.cs
src/Microsoft.AspNetCore.OData/Routing/Template/ODataPathTemplate.cs

Removing cast to KeySegmentTemplate so we get path segment key and parenthesis as well.

closes #125: removed cast to KeySegmentTemplate

---

sample/ODataRoutingSample/Controllers/v1/CustomersController.cs
src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Query/ActionResult/ActionResultTests.cs

- Added `QueryNodeKind.Count` as a valid option on  `ValidateSingleValueNode`
- Added e2e tests for $count in $filter
- Fixed missing Id's in customer list on ODataRoutingSample

#74 count in filter throws not supported

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataServiceCollectionExtensions.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryRequestMiddleware.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Commons/WebHostTestFixtureOfT.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/CustomQueryOptionsParserTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/QueryRequest/DollarQueryTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Fixes test failing subsequent to porting feature to support passing of query options in request body
Related to #119

Fix test failing after porting feature to OData 8.0-beta

---

src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataInputFormatter.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
test/Microsoft.AspNetCore.OData.Tests/Edm/EdmPrimitiveHelperTests.cs

Incorrect Assert in ConvertPrimitiveValue
LoggerError unnecessarily adds an additional frame to call stack
Fixes #131 
Fixes #140 
Change `ConvertPrimitiveValue` to simply call `Convert.ChangeType` and catch the common exceptions that indicate a type conversion is not allowed, then throw a corresponding `ValidationException`.
Update test cases to cover almost all of the code paths.
**Note**: `ConvertPrimitiveValue_NonStandardPrimitives_Data` is shared by tests for other methods with slightly different semantics, so the two tests vectors cannot be merged.
Rewrite the Throw test cases to use a common simplified test method.

Incorrect Assert in ConvertPrimitiveValue

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs
test/Microsoft.AspNetCore.OData.Tests/Scenarios/OpenComplexTypeTests.cs
test/Microsoft.AspNetCore.OData.Tests/Scenarios/OpenEntityTypeTests.cs

- Add more tests for dynamic property support in `ODataResourceSerializer`.
- Fixed a potential bug where a dynamic property with null value could be added to the resource even if it had the same name as an existing declared property
- Allowed null dynamic properties by default (see explanation below for more context)
There's a test called `CreateResource_Works_ToAppendNullDynamicProperties_ForOpenEntityType()`, based on the name, I assume that it should verify that dynamic properties with null values are added to the resource. However, the test actually verifies that dynamic properties with null values are actually *not* included in the resource. So I was confused about what the expected behaviour is.
Looking at the existing code, it seems that null dynamic properties are not allowed by …

Add ODataResourceSerializer tests and fixes for dynamic property support

---

src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

Fix for properties with new modifier (first property in collection is always current, not base class)

Fix AmbiguousMatchException for properties with new modifier

---

src/Microsoft.AspNetCore.OData/Deltas/DeltaOfT.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.Tests/Deltas/DeltaTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Recent PR to WebAPI added the new `Delta<T>` property `UpdateableProperties`.
AspNetCoreOData should have a consistent API surface area with WebAPI.
Fix:
- Diff `DeltaOfT.cs` and `DeltaOfTStructuredType.cs` and apply all new src changes, fix new code warnings
- Diff `DeltaTest.cs` and apply all new test changes, fix new code warnings
- Full test runs and fix: xmldocs, PublicAPI files

DeltaOfT out of sync with WebAPI: missing UpdatableProperties

---

src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/Expressions/ISelectExpandBinder.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinderContext.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ConcurrentQuery/ConcurrentQueryController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ConcurrentQuery/ConcurrentQueryODataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ConcurrentQuery/ConcurrentQueryTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

Fixes #304 
The main changes:
- Make `SelectExpandBinder` public.
- Add a new interface `ISelectExpandBinder` and make `SelectExpandBinder` inherit the interface.
- Add a new class `SelectExpandBinderContext` to wrap all properties needed by the `ISelectExpandBinder`.
- Register `ISelectExpandBinder` to the dependency injection container.
If a customer has their own custom implementation e.g `MySelectExpandBinder`, 
The `MySelectExpandBinder`  class should implement  `ISelectExpandBinder` directly or inherit from `SelectExpandBinder`.
*First option:*
```
public class MySelectExpandBinder : ISelectExpandBinder
{ 
} 
``` 
*Second option:*
```
public class MySelectExpandBinder : SelectExpandBinder
{ 
} 
```
In the first option, the customer will write their own implementation of all methods. …

Redesign SelectExpandBinder to allow customizations

---

src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderHelper.cs

This will fix the issue #85 by using property parameterization if possible for DateTimeOffset conversions.

Fixed issue #85: DateTime Created with too Much Decimal Precision Causing SQL Query to Fail

---

src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataModelBinderConverter.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/ODataModelBinderConverterTests.cs

If the function parameter, marked with [FromODataUri] has custom type in the model (TypeDefinition) it could still be processed as a primitive (cause it has primitive underlying type)

Added possibility to bind params of custom type

---

src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.Tests/Query/EnableQueryAttributeTests.cs

It seems the issue exists and was not patched in AspnetCoreOData.
https://stackoverflow.com/questions/69910220/create-custom-response-in-net-core-5-with-odata-8-controller.
Using `IStatusCodeActionResult` means multiple requests will be able to be checked. Users can now send JsonActionResult and other instances that implement `IStatusCodeActionResult` for their errors and have the errors propagated.

Migrate https://github.com/OData/WebApi/pull/2512 to AspNetCoreOData.

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataOptions.cs
test/Microsoft.AspNetCore.OData.Tests/ODataOptionsTests.cs

Fix #382 
This PR strips leading and trailing forward slashes from the OData path route prefix before registering route components service provider. This avoids the issues mentioned in #382 which result in the route prefix with leading slashes not being routed to OData endpoints. Route prefix with trailing slashes were causing an exception to be thrown because it would be combined with the endpoint path leading to 2 consecutive forward slashes.

Trim forward slashes from route prefix

---

sample/ODataSampleCommon/ODataEndpointController.cs
src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs

This PR changes all occurrences of "none OData" (referring to "not of OData type") to the correct "non-OData" wording.
Fixes #427

✏️ Fix 'none OData' -> 'non-OData' typo

---

src/Microsoft.AspNetCore.OData.Nightly.nuspec
src/Microsoft.AspNetCore.OData.Release.nuspec
src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs
src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
src/Microsoft.AspNetCore.OData/Extensions/SerializableErrorExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataPrimitiveSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/ClrCanonicalFunctions.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderHelper.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.SingleValueFunctionCall.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.cs
src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DateOnlyTimeOnly/DateAndTimeOfDayWithEfTest.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
test/Microsoft.AspNetCore.OData.Tests/Microsoft.AspNetCore.OData.Tests.csproj

#413 
Support DateOnly & TimeOnly new types defined in .NET 6.
1) Add the .NET 6.0 target framework to introduce new types (DateOnly and TimeOnly)
2) Support serialize of DateOnly & TimeOnly as "Date" and "TimeOfDay"
3) Support deserialize of DateOnly & TimeOnly from "Date" and "TimeOfDay".
4) Support the query option on DateOnly & TimeOnly, for example $filter.
To be clear: EF core 6.0 doesn't support DateOnly and TimeOnly. See https://github.com/dotnet/efcore/issues/24507

Support DateOnly and TimeOnly

---

src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs

This PR simplifies type mapping registrations by extracting a common method that enforces the ordering rules of nullable vs non-nullable type registrations.
This should prevent mistakes when managing these types or introducing new types in the future as well as reduce the overall amount of code duplication in the class.

♻️ Nullable and non nullable type mapping registration simplification

---

src/Microsoft.AspNetCore.OData/Deltas/DeltaOfT.cs
test/Microsoft.AspNetCore.OData.Tests/Deltas/DeltaTests.cs
test/Microsoft.AspNetCore.OData.Tests/Models/NewCustomerDataContract.cs
test/Microsoft.AspNetCore.OData.Tests/Models/NewCustomerUnmapped.cs

Same issue as WebApi 2532
Fixes #347
Ported from WebAPI.
**Notes**
The two new test classes are split into separate files due because the monolithic TestDataModels doesn't exist in this repro
Ported from master to main

Unmapped properties are in Delta<T>

---

src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs

The issue here is that the backing field _selectExpandClause isn't always initialized by the time ApplyTo is called unless the caller accesed the public SelectExpandClause property themselves. This causes the call to binder.ApplyBind to throw an ArgumentNullException.

Fix ArgumentNullException in SelectExpandQueryOption

---

src/Microsoft.AspNetCore.OData/Batch/ChangeSetRequestItem.cs
src/Microsoft.AspNetCore.OData/Batch/DefaultODataBatchHandler.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs
src/Microsoft.AspNetCore.OData/Batch/ODataBatchRequestItem.cs
src/Microsoft.AspNetCore.OData/Batch/OperationRequestItem.cs
src/Microsoft.AspNetCore.OData/Batch/UnbufferedODataBatchHandler.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.E2E.Tests/Batch/DefaultODataBatchHandlerController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Batch/DefaultODataBatchHandlerTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Batch/UnbufferedODataBatchHandlerTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Fixes #360
Fixes #481
Fixes #365
-Handle relative references in $batch by making URL absolute before copying.
-Allow requests within a batch to reference other requests within the batch whether or not they are in the same changeset.
-Added a using for ODataMessageReader in UnbufferedODataBatchHandler.
Work remaining:
[x] Add Tests
[x] Fix Reference Handling in UnbufferedODataBatchHandler.

Fix reference handling in $batch

---

src/Microsoft.AspNetCore.OData/Edm/EdmModelExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Routing/Conventions/EntityRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/EntitySetRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/SingletonRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/ActionRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/EntityRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/EntitySetRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/FunctionRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/SingletonRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/ODataRouteOptionsTests.cs

I am working with an API which uses camel case OData action names but these are not found because the routing is case sensitive. For example, the following will not work:
```diff
// sample/ODataCustomizedSample/Models/EnumsEdmModel.cs:75
- var actionConfiguration = employee.Action("AddSkill");
+ var actionConfiguration = employee.Action("addSkill");
```
This fails because `OperationRoutingConvension` is case sensitive. Changing the following makes it work.
```diff
// src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs:91
- IEnumerable<IEdmOperation> candidates = context.Model.SchemaElements.OfType<IEdmOperation>().Where(f => f.IsBound && f.Name == operationName);
+ IEnumerable<IEdmOperation> candidates = …
```

Adding support for case insensitive action names

---

sample/ODataRoutingSample/Controllers/PeopleController.cs
src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/FunctionSegmentTemplateTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/KeySegmentTemplateTests.cs

#567
When send a request contains the escaped string in the string key or function parameter as follows
`Get: /People(FirstName='Goods',LastName='Zha%2Fngg')`
We should unescape it before going to the parsing step.

Issue #567: Escape character , for example ('/') is not proper handle at key or function in quoted string

---

src/Microsoft.AspNetCore.OData/Batch/ODataBatchReaderExtensions.cs

#349
Customers may retrieve the query from the main request ($batch) that will create IQueryFeature into the Main HttpContext, Once created, it will cache in the main HttpContext. We should remove IQueryFeature and don't pass that to the subrequest. Otherwise, the sub-request query string will never be used.

Issue #349: Per-request query options are not preserved with the new $batch execution

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/FunctionRoutingConventionTests.cs

issue #568
Describe the bug
when function/action name contains keyword "On", the operation convention can't correct parse the action name. 
/odata/SEChat/SE.GetStatusOnLineOfflineUser => error
/odata/SEChat/SE.StatusLineOfflineUserOn => error
What is in the PR:
1) Search the operation using the whole action name first, if found, use it.
2) Split the action name, and search again.

issue #568: Error when function/action name contains keyword "On"

---

src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterHelper.cs
src/Microsoft.AspNetCore.OData/Routing/Template/ActionSegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/FunctionSegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ComplexTypeTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/ActionSegmentTemplateTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/FunctionSegmentTemplateTests.cs

Fixes #571 
The target navigation source is unresolved at the time of initializing an `ActionSegmentTemplate` and a `FunctionSegmentTemplate`. For that reason, the `NavigationSource` property of the `ODataSegmentTemplate` is initialized to `null`. Subsequently when we create an `OperationSegment` from the `TryTranslate` method of either of the two templates, the `EdmType` and `EntitySet` properties of the segment are initialized to null. This is the reason for the error exhibited in the [reported issue](https://github.com/OData/AspNetCoreOData/issues/571).
We fix the issue in this PR by using the entity set annotation to get the target navigation source. This annotation is set when `ReturnsFromEntitySet` method (and similar variants) are called when using the model builder to initialize …

Support FromBody parameters with actions and functions

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson/ODataNewtonsoftJsonMvcBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests/ODataNewtonsoftJsonMvcBuilderExtensionsTests.cs

#587
Fix the issue by calling AddODataNewtonsoftJson with null.
Add the test cases.

Fix issue #587: AddODataNewtonsoftJson should call AddODataNewtonsoftJson with null

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ODataQueryValidator.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/SelectExpandQueryOptionTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/ODataQueryValidatorTest.cs

Fixes https://github.com/OData/AspNetCoreOData/issues/620

Fixing ArgumentNullException on empty select/expand

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Batch/ContentIdToLocationMappingTests.cs

*This pull request fixes https://github.com/OData/odata.net/issues/2442.*
Resolve ContentID in odata.bind annotation
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Resolve ContentID in odata.bind annotation

---

sample/ODataAlternateKeySample/WeatherForecast.cs
sample/ODataCustomizedSample/ODataCustomizedSample.csproj
sample/ODataDynamicModel/ODataDynamicModel.csproj
sample/ODataNewtonsoftJsonSample/ODataNewtonsoftJsonSample.csproj
sample/ODataRoutingSample/ODataRoutingSample.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Microsoft.AspNetCore.OData.E2E.Tests.csproj
test/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests.csproj
test/Microsoft.AspNetCore.OData.TestCommon/Microsoft.AspNetCore.OData.TestCommon.csproj
test/Microsoft.AspNetCore.OData.Tests/Microsoft.AspNetCore.OData.Tests.csproj

See related issue #661.
1) Remove .NET 5 for sample and test projects
2) Update to .NET 6 for sample and test projects.
We should remove for .NET 5 and coming out of support .NET Core App 3.1 for the product projects later.

Remove .net 5 and update to .net 6 for samples and test projects

---

sample/ODataAlternateKeySample/Controllers/CustomersController.cs
sample/ODataAlternateKeySample/Controllers/OrdersController.cs
sample/ODataAlternateKeySample/Controllers/PeopleController.cs
sample/ODataAlternateKeySample/Models/EdmModelBuilder.cs
sample/ODataAlternateKeySample/readme.md
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml

Update alternate key sample to support core alternatekey term.

Update alternate key sample to support core alternatekey term

---

src/Microsoft.AspNetCore.OData/Common/Error.cs
src/Microsoft.AspNetCore.OData/Results/BadRequestODataResult.cs
src/Microsoft.AspNetCore.OData/Results/ConflictODataResult.cs
src/Microsoft.AspNetCore.OData/Results/NotFoundODataResult.cs
src/Microsoft.AspNetCore.OData/Results/UnauthorizedODataResult.cs
src/Microsoft.AspNetCore.OData/Results/UnprocessableEntityODataResult .cs

According to the [spec](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_ErrorResponseBody),
the error code is service defined and MAY be different from the HttpCode. So the validation that we previously added is not valid.
*Spec*
```
The representation of an error response body is format-specific. It consists at least of the following information:
·code: required non-null, non-empty, language-independent string. Its value is a service-defined error code. This code serves as a sub-status for the HTTP error code specified in the response.
·message: required non-null, non-empty, language-dependent, human-readable string describing the error. The [Content-Language](http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#sec_HeaderContentLan …
```

Remove ErrorCode validation

---

src/Microsoft.AspNetCore.OData/Extensions/GetNextPageHelper.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingTests.cs

*This pull request fixes https://github.com/OData/WebApi/issues/2493.*
Maintain case for parameter alias in generated nextLink
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Maintain case for parameter alias in generated nextlink

---

src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/Query/ComputeQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ComputeQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/CountQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ODataQueryValidator.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

issue #730
Enable to validate $compute if AllowedQueryOptions has correct setting.

Enable $compute allowed settings

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

*This pull request fixes https://github.com/OData/WebApi/issues/2728.*
*Briefly describe the changes of this pull request.*
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Fix serialization issue affecting nested complex property

---

src/Microsoft.AspNetCore.OData/Deltas/DeltaOfT.cs
src/Microsoft.AspNetCore.OData/Edm/EdmModelExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/DeserializationHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.Tests/Formatter/Deserialization/ODataResourceDeserializerTests.cs

Issue #743 
Enable the deep update for the nested delta collection.
Request Header:
```txt 
Content-Type: application/json
OData-Version: 4.01
OData-MaxVersion: 4.01
```
Patch to single entity with nested delta collection:
```json
{
"name":"anothertest",
"@id": "Order(2)",
"items@delta":[
{
"@id": "OrderItems(2, 1)",
"price":0
},
{
"@removed":{
"reason":"deleted"
},
"@id": "OrderItems(2, 2)"
}
]
}
```
Patch to single entity with nested collection:
```json
{
"name":"anothertest",
"@id": "Order(2)",
"items":[
{
"price":0
},
{
"price":1
}
]
}
```

Enable the nested delta collection deep update

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson/JsonPropertyNameMapper.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/Query/Container/IPropertyMapper.cs
src/Microsoft.AspNetCore.OData/Query/Container/JsonPropertyNameMapper.cs
src/Microsoft.AspNetCore.OData/Query/Container/NamedPropertyOfT.cs
src/Microsoft.AspNetCore.OData/Query/Wrapper/SelectExpandWrapper.cs
test/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests/JsonPropertyNameMapperTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Container/JsonPropertyNameMapperTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Container/PropertyContainerTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Wrapper/SelectExpandWrapperTest.cs

Fixes https://github.com/OData/AspNetCoreOData/issues/727
**Cause of the bug**
I found that when using $expand, the MapProperty methods of the default implementations for IPropertyMapper (for System.Text.Json and Newtonsoft.Json) contain code to interpret attributes applied to fields in the view model on their own. That is, they do not rely on the standard libraries to serialise the object, apply attributes, etc. 
Also, the only attribute they support is the property to rename a field - JsonProperty for Newtonsoft.Json, JsonPropertyName for System.Text.Json. Every other attribute would be ignored, including JsonIgnore. This explains why the bug is happening.
**Solution in this pull request**
1. Updated the MapProperty methods, so they check whether the field has the JsonIgnore attribute, …

fixes issue 727 [JsonIgnore] attribute ignored when using $expand

---

src/Microsoft.AspNetCore.OData/Routing/Conventions/ActionRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/FunctionRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs

Correct operation routing conventions docs - key segment does not apply to singletons

Correct operation routing conventions docs

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/Query/ComputeQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/CountQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/FilterQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/OrderByQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/SkipQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/SkipTokenQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/TopQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ComputeQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/CountQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ODataQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/OrderByQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/SelectExpandQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/SkipQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/SkipTokenQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/TopQueryValidator.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/OrderByQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/SelectExpandQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/SkipQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/TopQueryValidatorTest.cs

#issue #767
This is part of refactoring of issue #767.

Move Get Query validator as ODataQueryContext extension methods

---

sample/ODataAlternateKeySample/Models/AlternateKeyRepositoryInMemory.cs
src/Microsoft.AspNetCore.OData/Common/StringExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/ODataTemplateTranslateContext.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/KeySegmentTemplateTests.cs

See details at:  issue #796
When we retrieve the value from Request route values, it's unescaped. We don't need to unescape it again.
But for the Query option, we retrieve it from query string, it's not unescaped. we should unescape it.

Fix issue #796: Request path segments gets double unescaped

---

sample/ODataRoutingSample/Controllers/v1/OrganizationsController.cs
src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.Tests/ODataOptionsTests.cs

#812
1) Enable EnableReadingODataAnnotationWithoutPrefix by default
2) Add samples for nested DeltaDeletedResource

fixes #812: Support nested DeltaDeletedResource

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/Validator/SelectExpandQueryValidator.cs

fixes #829, SelectExpandQueryValidator throws when $selecting complex property

---

src/Microsoft.AspNetCore.OData/Edm/NavigationSourceLinkBuilderAnnotation.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DerivedTypes/DerivedTypesControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DerivedTypes/DerivedTypesDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DerivedTypes/DerivedTypesTests.cs

*This pull request fixes https://github.com/OData/AspNetCoreOData/issues/797.*
Fix wrong links generated for derived type with navigation property when `odata.metadata=full`. When `odata.metadata=full` is specified, the type-cast segment is wrongly appended to the resource id.
When that happens, since ODL also appends the type-cast segment, you end up with the response payload looking as follows:
```json
{
"@odata.context": "http://localhost:5219/odata/$metadata#Customers/ODataAlternateKeySample.Models.GoldCustomer/$entity",
"@odata.type": "#ODataAlternateKeySample.Models.GoldCustomer",
"@odata.id": "http://localhost:5219/odata/Customers(1)/ODataAlternateKeySample.Models.GoldCustomer",
"@odata.editLink": "Customers(1)/ODataAlternateKeySample.Models.GoldCustomer/ODataAlternateKeySample.Mode …
```

Fix wrong links generated for derived type with navigation property when odata.metadata=full

---

src/Microsoft.AspNetCore.OData/Edm/EdmHelpers.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataOptions.cs
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/DefaultQueryConfigurations.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryContext.cs
src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/CountQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/OrderByQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/SelectExpandQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/SkipTokenQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/TopQueryValidator.cs
test/Microsoft.AspNetCore.OData.TestCommon/MockServiceProvider.cs
test/Microsoft.AspNetCore.OData.Tests/ODataOptionsTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/EnableQueryAttributeTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/DefaultSkipTokenHandlerTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/FilterQueryValidatorTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/OrderByQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/SelectExpandQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/SkipTokenQueryValidatorTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/ValidationTestHelper.cs

fixes #834
1. Add DefaultQueryConfigurations class
2. Use it in ODataOptions (a public api changes)
3. change the related test codes.
Benefit:
1) It's a mistake to use DefaultQuerySetting from ModelBuilder ( I think)
2) Now, we can add other configuration, for example $compute, $search.

fixes #834, add DefaultQueryConfigurations class

---

src/Microsoft.AspNetCore.OData/Query/ODataQueryContext.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandTests.cs

Fixes https://github.com/OData/WebApi/issues/2748
We set the default `MaxExpansionDepth` when the `Validate` method of the `ODataQueryOptions` object is called. The problem currently is that when the `MaxExpansionDepth` is overridden, for instance by assigning the value from the `EnableQuery` attribute (`[EnableQuery(MaxExpansionDepth = 4)]`), we call the `Validate` method before the `AutoExpand` navigation properties have been added to the `SelectExpandQueryOption` object. For that reason, the specified `MaxExpansionDepth` ends up not being respected for the auto-expanded navigation properties.
This pull request fixes that by calling `ODataQueryOptions.AddAutoSelectExpandProperties` prior to validating the `SelectExpand` query option.

AutoExpand does not expand beyond non-default MaxExpansionDepth

---

test/Microsoft.AspNetCore.OData.E2E.Tests/DateTimeOffsetSupport/DateTimeOffsetController.cs

`DateTimeOffsetTest.CreateFileEntity_Works_UsingDifferentPropertyNameCase` fails when the locale is not United States (I'm in the UK), so I switched to using the DateTimeOffset constructor rather than parsing a US format date time string.

Make a datetimeoffset support test culture agnostic

---

src/Microsoft.AspNetCore.OData/Abstracts/IODataFeature.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/EnableQueryAttributeTests.cs

fixes #825.
Add another design comparing to #833.

fixes #825, add protected virtual to extend OData query option creating within EnableQueryAttribute

---

src/Microsoft.AspNetCore.OData/Edm/EdmModelExtensions.cs

This fixes an issue where the NavigationPropertySegment would have the wrong NavigationSource, resulting in an arcane error in certain scenarios because the associated entity type was wrong. The modified method is effectively a copy from [odata.net EdmExtensionMethods](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/EdmExtensionMethods.cs#L32), and it isn't clear why this line deviated.

fix: correctly find the target of a containment navigation property

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Routing/Conventions/EntitySetRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/NavigationRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/PropertyRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/ODataRouteOptions.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/EntitySetRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/NavigationRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/PropertyRoutingConventionTests.cs

Fixes #611, 
Try to add configuration for $count, $value conventional routing.

Fixes #611, add configuration for $count, $value conventional routing

---

src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingTests.cs

*This pull request fixes https://github.com/OData/WebApi/issues/1943, fixes https://github.com/OData/WebApi/issues/2041, and fixes https://github.com/OData/WebApi/issues/2561*
Consider a simple scenario involving a data sample comprising of `Id` key field and a non-unique nullable field `CreditLimit`:
| Id | CreditLimit |
| -- | ------------ |
| 1 | null |
| 2 | 2 |
| 3 | null |
| 4 | 30 |
| 5 | null |
| 6 | 35 |
| 7 | 5 |
| 8 | 50 |
| 9 | 25 |
From the controller action, we could configure a page size of 2:
```csharp
[EnableQuery(PageSize = 2)]
public ActionResult<IEnumerable<S1Customer>> Get()
{
return new List<S1Customer>
{
new S1Customer { Id = 1, CreditLimit = null },
new S1Customer { Id = 2, CreditLimit = 2 },
new S1Customer { Id = 3, CreditLimit = null },
new S1Customer { Id = 4, …
```

Fix skiptoken paging issue when combined with $orderby involving nullable property

---

src/Microsoft.AspNetCore.OData/Edm/ODataNullValueExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataEnumSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataPrimitiveSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml

Add ODataNullValueExtensions and use it during serializer

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataOptions.cs
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/DefaultQueryConfigurations.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Fixes #875
Let's take the suggestion from @commonsensesoftware to avoid the breaking changes.

Re-add the removed 'QuerySettings' to avoid breaking changes.

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Wrapper/ODataPrimitiveWrapper.cs
src/Microsoft.AspNetCore.OData/Formatter/Wrapper/ODataReaderExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Wrapper/ODataResourceSetWrapper.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.Tests/Formatter/Wrapper/ODataPrimitiveWrapperTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Wrapper/ODataReaderExtensionsTests.Untyped.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Wrapper/ODataReaderExtensionsTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

fixes #907.
also part of fixes #885. (No breaking changes)
Enable read the untyped collection.
For example:
```json
{
"awsTag":[
null,
{
"X1": "Red",
"Data": {
"D1": 42
}
},
"finance",
"hr",
"legal",
43
]
}
```
where, awsTag could be a dynamic property, it contains primitive value item, resource value item.
ODL reads it and returns:
1) ODataReaderState.Primitive  for primitive value in collection
2) ODataReaderState.ResourceStart  for resource value in collection.
3) It also can contain collection value item again in the collection.
This PR is to handle the above scenario.

#907: Enable read the untyped collection

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Results/CreatedODataResult.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Fixes #897 
Port from https://github.com/OData/WebApi/pull/2765

Make CreatedODataResult inherit from ObjectResult

---

sample/ODataRoutingSample/Controllers/PeopleController.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs

fixes #923
1) Enable using ODataValue to write Untyped property directly
2) And add test cases to verify the collection in collection

fixes #923 Enable using ODataValue to write Untyped property directly

---

src/Microsoft.AspNetCore.OData/Query/Container/JsonPropertyNameMapper.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ActionResults/ActionResultController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ActionResults/ActionResultODataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ActionResults/ActionResultTests.cs

fixes #921
1) Fix the error when using $compute in non-odata scenario:
```C#
Microsoft.OData.ODataException: Could not find a property named '{{propertyName}}' on type '{{entityType}}'.
```
2) Fix the problem in `JsonPropertyNameMapper.MapProperty(...)` if we have $compute in the query option.
3) Add test cases to cover it.

fixes #921, Enable $compute in non-odata path using ODataQueryOptions<T> directly

---

src/Microsoft.AspNetCore.OData/Formatter/LinkGenerationHelpers.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingTests.cs

This pull request ports [this 7.x fix](https://github.com/OData/WebApi/pull/2771) to 8.x

Fix invalid partial json generated when serverside paging is applied in multi-level containment scenarios

---

src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/DefaultSkipTokenHandlerTests.cs

Based on issue #616 which I also encountered, I would like to propose this fix.
As I am not completely aware of side-effects that using only `edmProperty.Name` could have, I relied on a safe way to rollback to the EDM property name instead of the CLR one if the latter is not found.
https://github.com/OData/AspNetCoreOData/blob/10a246671b6312fd234151c47cc91787da5cb171/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#LL136C1-L145C18
I tested this change with my current project, but I suspect that some unit tests might have to be "doubled" with a `builder.EnableLowerCamelCase()` scenario to check for regressions on property retrieval when using a lowercased convention.
edit: Also tested along with the `[DataContract]` and `[DataMember]` attributes which create aliases …

Potential fix for issue #616

---

sample/ODataDynamicModel/Extensions/EntitySetWithKeyTemplateSegment.cs
sample/ODataDynamicModel/Extensions/MyDataSource.cs
sample/ODataDynamicModel/Extensions/NavigationTemplateSegment.cs

This PR provides a solution to this issue: https://github.com/OData/AspNetCoreOData/issues/691
The updates to this sample ensures that `DetailInfo` navigation property is properly set and I have added a contained navigation property `ContainedDetailInfo`.

update dynamic sample

---

src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

Original PR #647 
Fixes [#2443](https://github.com/OData/WebApi/issues/2443)

Fix orderby with PageSize on derived types

---

src/Microsoft.AspNetCore.OData/Results/UpdatedODataResult.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

This pull request fixes #972 and fixes #434.
Make `UpdateODataResult` inherit from `ObjectResult`.

Make UpdateODataResult inherit from ObjectResult

---

src/Microsoft.AspNetCore.OData/Query/Validator/ODataQueryValidator.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

This PR fixes https://github.com/OData/AspNetCoreOData/issues/945, #984 
This fix makes this work: 
```url
http://localhost:5000/odata/Orders?$apply=groupby((Customer/Name), aggregate($count as OrderCount, TotalAmount with sum as Total))&$orderby=Total desc
```
Like you can use the output of $apply transformations, `Total`,  in this case to perform subsequent transformations, `$orderby` in this case. 
This is how the `ApplyClause` property looks like: 
```c#
public ApplyClause ApplyClause
{
get
{
if (_applyClause == null)
{
_applyClause = _queryOptionParser.ParseApply();
}
return _applyClause;
}
}
```
So what happens when this is called: `if (options.Apply?.ApplyClause != null)`.  if `ApplyClause` is null,which will be null at this point, then the `ParseApply` gets called which parses the …

Make output set of $apply transformations available for subsequent transformations or other query operators

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs

There are cases where we don't have a URL when writing a collection of nested entities. This may be, for example, because there was no navigation property binding for the collection, because the collection was returned as the child of a complex type returned by a function, or because the entities were "transient".
In any case, lack of a URL should not prevent us from writing the nested data, if available.
Currently, we conflate writing the content with writing the url and, if we can't determine a navigation source, we skip writing the nested content entirely (although there are other cases where, even though we have a navigation source, we can't determine the url, so we already have cases where we write nested content without the url but only if we have a navigation source.)
This PR …

Support writing nested entities without a navigation source.

---

src/Microsoft.AspNetCore.OData/Routing/Conventions/AttributeRoutingConvention.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/AttributeRoutingConventionTests.cs

fixes #986: pass Order value to selector model generated
Customer maybe specify the order value in the attribute, we should pass this value to the new selector model generated.
```C#
[Route("/Data(Key1={Key1}, Key2={Key2})", Order = -1)]
public IActionResult GetOne(long Key1, string Key2)
{
..
}
```

fixes #986: pass Order value to selector model generated

---

src/Microsoft.AspNetCore.OData/Query/Expressions/BinderExtensions.cs
src/Microsoft.AspNetCore.OData/Query/Query/OrderByQueryOption.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

This PR Fixes #979 and #969 
Moved the `EnsureFlattenedProperties` method from `ApplyBind` in `BinderExtensions` class to `ApplyToCore` in `OrderByQueryOption` class. The reason for this is to avoid the `EnsureFlattenedProperties` being called more than once since it was in a foreach loop and was assigning null to FlattenedProperties on the second loop.

fix $apply with $groupby with more than one property & $top

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedTests.cs

fixes #931
If we have
```C#
public enum UserType {...}
```
But this enum is not defined in OData model.
Suppose we use this C# enum to assign a value for a untyped property or dynamic property, the result is empty resource.
Person p = new Person
{
Data = UserType.Admin  // System.Object Data {get;set;}
}
We get:
"Data": {},
This PR is to fix this issue.
To Be discussed: Shall we write the full-name of enum member as string into OData payload? @mikepizzo

fixes #931: Undeclared enum type value for untype value serialized as empty resource

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

This fixes the issue #1023 where all structural properties are removed from the generated SQL query when using `$expand` without `$select` in a `builder.EnableLowerCamelCase()` scenario.
Probably fixes the same issue when using aliases in an EdmModel with the `[DataMember(Name=...)]` attribute.

#1023 - Fix all structural properties ignored when using `$expand` without `$select` and camel cased property names

---

src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

This PR fixes https://github.com/OData/AspNetCoreOData/issues/1026
In this fix https://github.com/OData/AspNetCoreOData/pull/993 we added a fix to remove duplicate joins from the generated sql. This involved making updates to the Instance property of the expression to be created and only including structural properties. 
The changes led to this being generated: 
```c#
{ Instance = new Customer() {Id = $it.Id, Name= $it.Name}}
```
Instead of this: 
```c#
{ Instance = $it }
```
```c#
foreach (PropertyInfo prop in props)
{
foreach (var sp in structuralProperties)
{
if (sp.Name == prop.Name)
{
MemberExpression propertyExpression = Expression.Property(source, prop);
bindings.Add(Expression.Bind(prop, propertyExpression));
break;
}
}
}
```
This is the code that recreates the Instance to only …

fix binding readonly properties

---

src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/DefaultSkipTokenHandlerTests.cs

Hi,
We just encountered an issue related to the `EnableLowerCamelCase` feature, in a scenario where we issue a query with pagination enabled (using `$skiptoken`) and a **descending** `$orderby`.
The issue is situated here :
https://github.com/OData/AspNetCoreOData/blob/fce1c6121a2a88b5e34d650ed609b913415a6c68/src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs#L315
the keys in the dictionary do not match with the `key` variable because of the different casing. The same is happening with aliased properties.
It results in a false 'false' evaluation of the `if` condition, and the `else` branch of the if is evaluated, generating a wrong predicate on SQL side (ascending instead of descending)
The issue can be fixed here : …

Fix for bad ordering with `$skiptoken` enabled and `$orderby=... desc`

---

src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/ODataQueryOptionTests.cs

We use server-side paging feature and encountered an issue where OData applies stable ordering to the output dataset for $skip, $top, and EnableQueryAttribute.PageSize.
However, OData overlooks scenarios in which paging is defined through the EDM model, even though stable ordering logic should also be applied in such cases.
Although EnableQueryAttribute.PageSize is useful, it can become unwieldy in specific situations, especially when it propagates throughout all internal collections. This can lead to unexpected navigation through internal structures and retrieval of missing data. Additionally, issues may arise when constructing the @odata.nextLink for contained collections.

Stable ordering should be applied when using the EDM model for paging (in addition to EnableQueryAttribute.PageSize)

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DeltaToken/DeltaTokenControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DeltaToken/DeltaTokenDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DeltaToken/DeltaTokenQueryTests.cs

Fixes #1064, enable to write dynamic properties for changed/delta object

Fixes #1064, enable to write dynamic properties for changed/delta object

---

src/Microsoft.AspNetCore.OData/Formatter/ResourceContext.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs

Fixes #1071
Navigation links only get written when `MetadataLevel` is set to `ODataMetadataLevel.Full` or when `MetadataLevel` is set to `ODataMetadataLevel.Minimal` and the `NavigationLinkBuilder's` FollowsConvention property is set to false. The ODataWriter methods for writing navigation links get called every time even when the navigation links are not being written. Calling these methods leads to a lot of CPU usage and high latency when the navigation links are not being written. 
In this PR, I've added a bool property `WriteNavigationLinks` in the ResourceContext... The default value for this property is `false`. If the metadata level is set to full or minimal and FollowsConvention is set to false, then the `WriteNavigationLinks`
is set to true. Otherwise, it is set to false.
So, …

Write Nav links when metadata full

---

src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/IAsyncEnumerableTests/IAsyncEnumerableController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/IAsyncEnumerableTests/IAsyncEnumerableTests.cs

We added support for the `IAsyncEnumerable` interface. The current support can only be used like this: 
```c#
[HttpGet] 
[EnableQuery] 
public IAsyncEnumerable<Customer> Get() 
{ 
return this.context.Customers.AsAsyncEnumerable(); 
} 
```
This PR adds support for this format: 
```c#
[EnableQuery] 
public ActionResult<IAsyncEnumerable<Customer>> Get() 
{ 
var query = this.context.Customers.AsAsyncEnumerable(); 
return this.Ok(query); 
} 
```
In the second format, the declared type of the returned object is null `ObjectResult responseContent = actionExecutedContext.Result as ObjectResult`. This is the type that is used to determine how to retrieve items from the database during serialization. That's if the type is `IAsyncEnumerable<T>` then we use `await foreach` otherwise we just use a …

support ActionResult<IAsyncEnumerable<T>>

---

src/Microsoft.AspNetCore.OData/Edm/EdmModelAnnotationExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs

The CreateEtag method creates an ETag for a given entity.  This method is called for every resource and seems to take-up a lot of CPU time even in cases where ETags are not being created. 
This is how the CreateEtag method looks like: 
```c#
public virtual string CreateETag(ResourceContext resourceContext)
{
if (resourceContext == null)
{
throw Error.ArgumentNull(nameof(resourceContext));
}
if (resourceContext.Request != null)
{
IEdmModel model = resourceContext.EdmModel;
IEdmNavigationSource navigationSource = resourceContext.NavigationSource;
IEnumerable<IEdmStructuralProperty> concurrencyProperties;
if (model != null && navigationSource != null)
{
concurrencyProperties = model.GetConcurrencyProperties(navigationSource).OrderBy(c => c.Name);
}
else
{
concurrencyProperties = …
```

Perf-improvement: CreateEtag method

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/MetadataProperties/MetadataPropertiesController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/MetadataProperties/MetadataPropertiesDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/MetadataProperties/MetadataPropertiesDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/MetadataProperties/MetadataPropertiesEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/MetadataProperties/MetadataPropertiesTests.cs

This pull request fixes https://github.com/OData/odata.net/issues/2273.
In the described scenario, a `Site` entity type has a **contained** `Plants` navigation property. The `Plant` entity type in turn has a **contained** `Pipelines` navigation property. The `Pipeline` entity type in turn has a **non-contained** single-valued `Plant` navigation property.
The **non-contained** `Plant` navigation property is bound to the `Plants` **contained** entity set via the Edm path `Sites/Plants`:
```csharp
namespace Core
{
public abstract class EntityBase
{
[Key]
public int Id { get; set; }
public string Name { get; set; }
public Dictionary<string, object>? Attributes { get; set; }
}
public class Site : EntityBase
{
[Contained]
public IEnumerable<Plant>? Plants { get; set; }
}
public class Plant : …
```

Generate valid id/read/edit links for expanded non-contained resource with a contained navigation source

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataPrimitiveSerializer.cs

The `ConvertPrimitive` method checks if a primitive is a `Date`, `TimeOfDay`, `Char`, `UInt16`, `UInt32`, `UInt64`. `DateTime`, `char[]`, `XElement` and handles them differently.  
If a primitive type is not any of these types, then the value is returned. 
A lot of checks are done to check for the above-mentioned types which can be avoided if we return the value early if we know the type, we are dealing with is not any of the above-mentioned types that need special processing. 
Making this change leads to the following CPU improvements: 
Before:
After:

Update ConvertPrimitiveType method

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs

The `CreateStructuralPropertyBag` method begins by initializing an empty list of properties. It then iterates through the structural and computed properties in a resource, appending them to the empty list. Currently, the frequent invocation of the `AddWithResize(T)` method appears to be resource-intensive. To mitigate this, preallocating a list with a specific size helps minimize this expense.
CPU Usage before these changes
CPU usage after these changes:

Perf Fix : AddWithResize(T)

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs

This PR fixes some of the issues raised in this PR: https://github.com/OData/AspNetCoreOData/issues/1111: 
I've made the following updates to the `CreateEtag` method: 
- Set the initial value of the properties dictionary to null and initialize properties only within the foreach loop. This approach guarantees that the dictionary is instantiated only when concurrency properties are present.
- I excluded the OrderBy operation from the IEnumerable of concurrency properties to eliminate the cost associated with OrderedEnumerable.MoveNext(). Consequently, the existing approach retrieves the concurrent properties, orders them, and subsequently inserts them into a dictionary. If the dictionary preserves the order, the crucial factor lies in the manner in which properties are added to the …

Perf Fix CreateEtags

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/Nodes/OrderByClauseNode.cs
src/Microsoft.AspNetCore.OData/Query/Nodes/OrderByItNode.cs
src/Microsoft.AspNetCore.OData/Query/Nodes/OrderByNode.cs
src/Microsoft.AspNetCore.OData/Query/Nodes/OrderByOpenPropertyNode.cs
src/Microsoft.AspNetCore.OData/Query/Nodes/OrderByPropertyNode.cs
src/Microsoft.AspNetCore.OData/Query/Query/OrderByQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/OrderByModelLimitationsValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/OrderByQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/OrderByValidatorContext.cs
src/Microsoft.AspNetCore.OData/Query/Validator/QueryValidatorContext.cs
src/Microsoft.AspNetCore.OData/Query/Validator/QueryValidatorHelpers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ODataOrderByTest/OrderByAdvancedTest.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ODataOrderByTest/OrderByController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ODataOrderByTest/OrderByDataModel.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/Nodes/OrderByClauseNodeTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Nodes/OrderByOpenPropertyNodeTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/ODataQueryOptionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/OrderByQueryOptionTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/OrderByQueryValidatorTest.cs

Fixes #1126
Support odata query expression in $orderby. For example:
$orderby=tolower(name)
$orderby=year(Birthday)
....

Fixes #1126: enable built-in expression in $orderby

---

sample/ODataRoutingSample/Controllers/ProductsController.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Template/FunctionSegmentTemplateTests.cs

For example: using https://github.com/OData/AspNetCoreOData/tree/main/sample/ODataRoutingSample sample, and send request
http://localhost:5000/Products/Default.GetWholeSalary(order='2',name='key%253A')
Before this change:
The respose is:
After this change:
the response is:

Fixes #1131, doube unescaped for function parameters

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/Microsoft.AspNetCore.OData.Tests/Microsoft.AspNetCore.OData.Tests.csproj
tool/builder.versions.settings.targets

Update library version to 8.2.4 and ODL version to 7.20.0

Update version to 8.2.4

---

src/Microsoft.AspNetCore.OData/Routing/ODataPathExtensions.cs

Fix #1118 
Replaces the use of `ODataPathNavigationSourceHandler` in `ODataPath.GetNavigationSource` extension method with a simpler reverse loop of the path.
With `ODataPathNavigationSourceHandler`
- a new instance of the handler is allocated
- all the segments of the path are visited
- a `List<string>` is created and populated with the string representation of each path segment. This list is used to generate a string representation of the path via a `Path` property. But this property is not needed to determine the navigation source (it's also not used by existing code).
The new implementation scans the path segments from the end and stops as soon as it finds the navigation source because only the last navigation source in the path matters.
The `ODataPathNavigationSourceHandler` is …

Optimize `ODataPathExtensions.GetNavigationSource`

---

src/Microsoft.AspNetCore.OData/Edm/EdmModelExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/DeserializationHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataDeserializerContext.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceSetDeserializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Untyped/UntypedTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Deserialization/ODataResourceSetDeserializerTests.cs

fixes #954, enable to read the untyped value with odata.type annotated.
{
"data@odata.type": "#Edm.Guid",
"data":"40EE4E85-C443-41B2-9611-C55F97D80E84",
}
{
"data@odata.type":"#UntypedApp.Models.Gender",
"data": "Male"
}
{
"data":{
"@odata.type":"#Microsoft.AspNetCore.OData.E2E.Tests.Untyped.InModelAddress",
"City":"Redmond",
"Street":"156TH AVE"
}
}
{
"data@odata.type":"#Collection(Edm.Int32)",
"data":[
4,
5
]
}

fixes #954, enable to read the untyped value with odata.type annotated

---

test/Microsoft.AspNetCore.OData.Tests/Scenarios/UnicodeCharactersTests.cs

By changing the UnicodeCharactersTests.cs encoding from ISO-8859-1 to UTF-8.
❌ Before this commit:
```
dotnet test --filter "FullyQualifiedName~UnicodeCharactersTest" --framework net6.0 test\Microsoft.AspNetCore.OData.Tests\Microsoft.AspNetCore.OData.Tests.csproj
Determining projects to restore...
All projects are up-to-date for restore.
Microsoft.AspNetCore.OData -> C:\Projects\GitHub\AspNetCoreOData\bin\AnyCPU\Debug\net6.0\Microsoft.AspNetCore.OData.dll
Microsoft.AspNetCore.OData.TestCommon -> C:\Projects\GitHub\AspNetCoreOData\bin\AnyCPU\Debug\net6.0\Microsoft.AspNetCore.OData.TestCommon.dll
Microsoft.AspNetCore.OData.Tests -> C:\Projects\GitHub\AspNetCoreOData\bin\AnyCPU\Debug\net6.0\Microsoft.AspNetCore.OData.Tests.dll
Test run for …
```

Fix UnicodeCharactersTest

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceSetDeserializer.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Deserialization/ODataResourceSetDeserializerTests.cs

Fixes #1171.
1) Add the 'Definition'
2) Add a test case.

Fixes #1171: ODataResourceSetDeserializer type cast wrong

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Routing/ODataRoutingTests.cs

Fixes #1152,
if we have the logger enabled in the TryMatch. Otherwise, keep to throw exception.

Log the invalid key or function parameter 

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs

Fix multiple calls to GetGenericTypeDefinition in [ODataSerializerContext.cs](https://github.com/OData/AspNetCoreOData/compare/main...senioroman4uk:senioroman4uk/fix-is-delta-of-t?expand=1#diff-732b595c31c0f7e9b97687d1ab7bce7d1f35d3fc2ce9adfcec3ef13e1d373b99)
fixes #1188

Read Type.GetGenericTypeDefinition just once in _isDeltaOfT

---

sample/BenchmarkServer/Controllers/ProductsController.cs
src/Microsoft.AspNetCore.OData/Query/Container/TruncatedCollectionOfT.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/Container/TruncatedCollectionOfTTest.cs

After profiling our service that uses AspNetCore.OData with a huge page size of 3000. I've noticed a lot of time is spent inside TruncatedCollection overload for IQueryable
Since it uses List as a base class current initialization will resize quite a few times before reaching the page size. This PR attempts to fix this for some of the overloads were size of the page is known
fixes #1185

Set capacity for TruncatedCollection(IQueryable, int, boolean) overload

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/ODataQueryContext.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/Query/ComputeQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/CountQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/FilterQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/OrderByQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/SearchQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ODataOrderByTest/OrderByMoreTest.cs

Fixes #1190.
See details from the issue at: https://github.com/OData/AspNetCoreOData/issues/1190#issuecomment-1986299357

Fixes #1190: Enable case insensitive by default for query

---

pipelines/azure_pipelines.yml
pipelines/azure_pipelines_nightly.yml

Once merged, PRs against `main` should automatically trigger the rolling build pipeline.
I've also renamed the stages from `stage` to `Stage_1`.

Trigger pipeline on PRs against main

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSerializerTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Wrapper/ODataReaderExtensionsTests.Untyped.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Wrapper/ODataReaderExtensionsTests.cs
tool/builder.versions.settings.targets

Updated the ODL version to `8.0.0-rc.1`. Since `8.0.0-rc.1` had some breaking changes, I've also made some updates like: 
1. Updating `ODataResource.Properties` to a collection of `ODataPropertyInfo`

Update ODL versions to 8.0.0-rc.1

---

src/Microsoft.AspNetCore.OData/Query/Expressions/OrderByBinder.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.SingleValueFunctionCall.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.cs

Cause debugger to step through argument-check methods

Cause debugger to step through argument-check methods

---

src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterHelper.cs

This issue https://github.com/OData/AspNetCoreOData/issues/1320 revealed that we call synchronous `Dispose()` method in one of the code paths in `ODataOutputFormatterHelper`:
```
System.InvalidOperationException
An asynchronous operation is already in progress.
at System.Xml.XmlAsyncCheckWriter.CheckAsync()
at System.Xml.XmlAsyncCheckWriter.Flush()
at Microsoft.OData.ODataMetadataOutputContext.Dispose(Boolean disposing)
at Microsoft.OData.ODataOutputContext.Dispose()
at Microsoft.OData.ODataMessageWriter.Dispose(Boolean disposing)
at Microsoft.OData.ODataMessageWriter.Dispose()
at Microsoft.AspNetCore.OData.Formatter.ODataOutputFormatterHelper.WriteToStreamAsync(Type type, Object value, IEdmModel model, ODataVersion version, Uri baseAddress, MediaTypeHeaderValue contentType, HttpRequest …
```

Use `await using` for async disposal of message writer

---

src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/AutoExpand/AutoExpandTests.cs

Cherry-pick https://github.com/OData/AspNetCoreOData/commit/a77ed76dcb76d9a31e493f23b372c93d397dc061

Cherry-pick (a77ed76): Fix AutoExpand Issues with Capitalized $Expand System Query Options

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarFilter/DollarFilterController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarFilter/DollarFilterDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarFilter/DollarFilterDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarFilter/DollarFilterEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarFilter/DollarFilterTests.cs

Add dynamic single-valued property support for filter expressions
Scenarios:
- $filter={DynamicSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value}
- $filter={DynamicSingleValuedProperty}/{DynamicSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value}
- $filter={DynamicSingleValuedProperty}/{DeclaredSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value}
- $filter={DynamicSingleValuedProperty}/{DynamicSingleValuedProperty}/{DeclaredSingleValuedProperty} eq {value}
- $filter={DeclaredSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value}
- $filter={DeclaredSingleValuedProperty}/{DynamicSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value}
- $filter={DeclaredSingleValuedProperty}/{DeclaredSingleValuedProperty}/{DynamicSingleValuedProperty} eq {value} …

Add dynamic single-valued property support for filter expressions

---

src/Microsoft.AspNetCore.OData/Edm/ContainmentPathBuilder.cs
src/Microsoft.AspNetCore.OData/Formatter/LinkGenerationHelpers.cs
src/Microsoft.AspNetCore.OData/Query/Query/SelectExpandQueryOption.cs

Fixes #1336 : Regressions from refacturing from extension method EntityType() to EntityType property bug
If the navigation source is null, it throws nullreference exception. Change it to test the null first, then call the EntityType property.

Fixes #1336 : Regressions from refacturing from extension method EntityType() to EntityType property bug

---

src/Microsoft.AspNetCore.OData/Abstracts/ODataServiceCollectionExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.Tests/Abstracts/DefaultContainerBuilderTests.cs

Message reader and Writer have the wrong scope in the DI container.
This could cause some issues whenever users retrieve and write to them in the scope of a request.
Fixes #1337 by updating the dependencies to 8.0.2 as well as moving reader and writer settings to scoped.
This includes https://github.com/OData/odata.net/pull/3058

update DI settings

---

README.md
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj

This PR update `README` file to add the following:
- Add more links to ASP.NET OData documentation
- How to install `Microsoft.AspNetCore.OData` package using .NET CLI and Package Manager
It also update `csproj` file by adding `README.md` as the package readme file. This is to ensure README.md is package when generating NuGet package.
https://devblogs.microsoft.com/nuget/add-a-readme-to-your-nuget-package/ 
https://learn.microsoft.com/en-us/nuget/reference/msbuild-targets#packagereadmefile
1. `<PackageReadmeFile>README.md</PackageReadmeFile>`:
- This line specifies that the README.md file should be included as the readme file in the NuGet package. When someone views your package on NuGet.org, this README file will be displayed.
2. `<None Include="README.md" Pack="true" PackagePath="\"/>`: …

Add a README to NuGet package

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataEnumDeserializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataEnumSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsTest.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Deserialization/ODataEnumDeserializerTests.cs

*This pull request fixes [#1359](https://github.com/OData/AspNetCoreOData/issues/1359).*
Currently, the `ODataEnumSerializer` and `ODataEnumDeserializer` fails to convert multi-value Flag enums to LowerCamelCase as specified in `EnumMember` attribute. However, this works with single-value Flag enums.
Consider the following Flag enum:
```cs
[Flags]
[DataContract(Name = "exampleEnum")]
public enum ExampleEnum
{
[EnumMember(Value = "firstValue")]
FirstValue = 1,
[EnumMember(Value = "secondValue")]
SecondValue = 2,
[EnumMember(Value = "thirdValue")]
ThirdValue = 4
}
```
With the default ODataEnumSerializer, a `single-value` Flag enum like `ExampleEnum.FirstValue` is correctly converted to ("`firstValue`"). However, a `multi-value` Flag enum like `ExampleEnum.FirstValue | …

Fix Default ODataEnumSerializer and ODataEnumDeserializer Fails to Convert Multi-Value Flag Enum Values to Lower Camel Case

---

src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatter.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/ODataOutFormatterTests.cs

ODataOutputFormatter fix - Make WriteResponseBodyAsync fully asynchronous.
Updated WriteResponseBodyAsync in ODataOutputFormatter.cs to be asynchronous, improving efficiency and giving ability to clients to better handle the error (ODataException) if thrown by ms writer.
This update has the potential to resolve several issues related to serializers.

ODataOutputFormatter fix - Make WriteResponseBodyAsync fully async

---

src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Wrapper/ODataReaderExtensions.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Deserialization/ODataResourceDeserializerTests.cs

Fixes #1307 by handling a property without value gracefully when deserializing OData payloads

Fix subtle bug when deserializing property without value

---

src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderBase.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderHelper.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.SingleValueFunctionCall.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/QueryBinderTests.cs

Fixes https://github.com/OData/AspNetCoreOData/issues/1084
This PR will make it possible to create custom function for nullable types.
See PR #1090 with similar change for 8.x

Custom method can now have nullable parameters and nullable arguments for 9.x

---

pipelines/azure_pipelines.yml
tool/ValidateODataPackageVersions.ps1
tool/builder.versions.settings.targets

*This pull request fixes [#1387](https://github.com/OData/AspNetCoreOData/issues/1387).*
This change involves:
- Add PowerShell script to validate the OData Package version in `Microsoft.AspNetCore.OData.csproj` against the version in `builder.versions.settings.targets`.
- Add a step in the pipeline to validate the OData Package version by running a PowerShell script.
- Update ODataLibPackageDependency version to [8.2.3, 9.0.0)
This approach is to ensure that the OData Package version in the `Microsoft.AspNetCore.OData.csproj` file matches the version in `builder.versions.settings.targets` as we consider the option of moving away hardcoded `.nuspec` file:
https://github.com/OData/AspNetCoreOData/blob/df9c340d71e69511158069b86035c01f6696d978/src/Microsoft.AspNetCore.OData.Release.nuspec#L19 …

Validate ODL Version in csproj against builder.versions.settings.targets and update ODataLibPackageDependency to 8.2.3

---

src/Microsoft.AspNetCore.OData/Extensions/ActionModelExtensions.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/NavigationRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/PropertyRoutingConventionTests.cs

Fixes #1397: Conventional routing cannot identify the endpoint for action to query property without the key

Fixes #1397: Conventional routing cannot identify the endpoint for action to query property without the key

---

src/Microsoft.AspNetCore.OData/Query/ETag.cs
src/Microsoft.AspNetCore.OData/Query/ExpressionHelpers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/DerivedETagTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagsModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagsOtherTypesTest.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/JsonETagsTests.cs

Fixes #1332
A popular convention today for concurrency check fields is to use a `byte[]` field called `RowVersion` with a `Timestamp` or `ConcurrencyCheck` attribute.
However, when using such a field, the `queryOptions.ifNoneMatch.ApplyTo` call was having absolutely no effect. That's because `ApplyTo` was internally using `Expression.Equal` which is perfect for value types but doesn't fare very well against reference types or particularly Arrays.
I fixed this by adding a case for arrays that, through a helper method, generates an expression that performs a deep comparison.

Fixes #1332: Deep Comparison for Array-based Concurrency tokens.

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ETags/ETagsModel.cs

Fixes #1400
Fix regression where timestamp property is incorrectly expected in complex type.
Regression introduced in https://github.com/OData/AspNetCoreOData/pull/1365 after the call for `CreateTag` was moved to an execution path that handles complex nested resource as well.
CreateResource:
https://github.com/OData/AspNetCoreOData/blob/c860cdc6e4f63081bdefc16e4e21873952f8101f/src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs#L607
`CreateTag` method calls `GetConcurrencyProperties(IEdmModel, IEdmNavigationSource)`. When writing a complex nested resource, `ResourceContext.NavigationSource` will be initialized to the navigation source for the parent entity type. For that reason, the concurrency properties returned will be for …

Fix regression where timestamp property is incorrectly expected in complex type

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSetSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataResourceSetSerializerTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/SerializationTestsHelpers.cs

This PR fixes #1384 
The reading of ITruncatedCollection.IsTruncated (used by ODataResourceSetSerializer for nested resource sets) is postponed until after enumeration have completed.
This change is to support other implementations of ITruncatedCollection than the List<T> based TruncatedCollection<T>. Other implementations might not have the collection in memory when before enumeration starts and thus might not know if the data has been truncated like the List<T> based one.
Some tests have been added - both my attempt to write a unittest with Mocks and an E2E test.

Checking ITruncatedCollecton.IsTruncated after enumeration. Fixes #1384

---

src/Microsoft.AspNetCore.OData/Formatter/Value/EdmDeltaComplexObject.cs
src/Microsoft.AspNetCore.OData/Formatter/Value/EdmDeltaResourceObject.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

Mark `EdmDeltaResourceObject` and `EdmDeltaComplexObjects` types as obsolete. `EdmEntityObject` and `EdmComplexObject` respectively should be used instead.
Related to https://github.com/OData/AspNetCoreOData/issues/1429

Mark EdmDeltaResourceObject and EdmDeltaComplexObjects types as obsolete

---

src/Microsoft.AspNetCore.OData/Formatter/ODataOutputFormatterHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
src/Microsoft.AspNetCore.OData/Formatter/Value/EdmEntityObjectCollection.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Shipped.txt
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessExtensions.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Typeless/TypelessTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/Serialization/ODataSerializerContextTest.cs

Fixes #1412
Fix regression causing navigation properties to be auto-expanded in typeless scenarios
The challenge we face is that `EdmEntityObject`, `EdmComplexObject`, `EdmDeltaResourceObject`, `EdmDeltaComplexObject`, and `EdmDeltaDeletedResourceObject` (together with their typed `internal` equivalents `TypedEdmEntityObject` and `TypedEdmComplexObject`) all implemement `IDelta`, `IDeltaSetItem`, and `IEdmChangedObject` interfaces directly or indirectly.
Illustration:
```csharp
using Microsoft.AspNetCore.OData.Deltas;
using Microsoft.AspNetCore.OData.Formatter.Value;
using Microsoft.OData.Edm;
var orderEntityType = new EdmEntityType("NS", "Order");
var addressComplexType = new EdmComplexType("NS", "Address");
var orderEntityObject = new EdmEntityObject(orderEntityType);
var …
```

Fix regression causing navigation properties to be auto-expanded in typeless scenarios

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataEnumSerializer.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Enums/EnumsTest.cs

This PR addresses an issue with the `Flags enum` logic where the `bitwise AND` operation `(graphValue & flagValue) != 0` incorrectly matches combined flags when only specific flags are intended. 
The current logic `(graphValue & flagValue) != 0` checks if any of the bits in `flagValue` are set. While this works for simple flag checks, it fails when combined flags are involved. For example, if `Admin` is a combination of `Read, Write, and Execute`, checking for `Read and Write` using the current logic will also match Admin, which is not the intended behavior.
```cs
[Flags]
public enum AccessLevel
{
None = 0,
Read = 1,
Write = 2,
Execute = 4,
Admin = 7 // Read | Write | Execute
}
```
To resolve this issue, the logic has been updated to `(graphValue & flagValue) == flagValue`, which ensures …

Fix Enum Flag Logic to Correctly Match Specific Flags

---

test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

Revert changes to EntitySetAggregation tests to troubleshoot issue causing tests to hang on AzDO

Revert changes to EntitySetAggregation tests to troubleshoot issue causing tests to hang on AzDO

---

src/Microsoft.AspNetCore.OData/Routing/ODataPathSegmentHandler.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/Regressions/LocationHeaderTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/ODataPathSegmentHandlerTests.cs

ODataPathSegmentHandler is used to construct odata.id, odata.editLink, odata.readLink as well as Location header.
This PR ensures that key values are escaped for all unsafe url chars.
Uri.EscapeDataString is used to escape key values to allign with the escaping used by ODL Client.
This PR fixes issue #1390.

Fixes #1390: Ensuring Url safe string key values. Aligning with ODL Client.

---

src/Microsoft.AspNetCore.OData/Routing/Conventions/AttributeRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Template/KeySegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/SegmentTemplateHelpers.cs

According to [CA2254 docs](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2254) template of a log message should be a static expression.
There are a number of places where instead of logging it might cause and causes in my case subsequent formatting exception.

CA2254 fixes possible formatting errors

---

src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/Query/OrderByQueryOption.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DollarCompute/DollarComputeTests.cs
tool/builder.versions.settings.targets

Fixes #1483.
Let's focus on the 9.3.x version. Since it's regression, let's release it as 9.3.2.
After that, I will port it to the main branch.

Fixes #1483: Regression with computed in $orderby with 'Could not find a property named xxx on ....'

---

sample/ODataMiniApi/AppModels.cs
sample/ODataMiniApi/CustomersAndOrders.http
sample/ODataMiniApi/Endpoints/CustomersEndpoints.cs
src/Microsoft.AspNetCore.OData/Deltas/DeltaOfT.cs
src/Microsoft.AspNetCore.OData/Extensions/HttpContextExtensions.cs
src/Microsoft.AspNetCore.OData/Extensions/HttpRequestExtensions.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataActionParameters.cs
src/Microsoft.AspNetCore.OData/Formatter/ODataUntypedActionParameters.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataMiniOptions.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/ODataQueryContext.cs
test/Microsoft.AspNetCore.OData.Tests/Deltas/DeltaTests.cs
test/Microsoft.AspNetCore.OData.Tests/Extensions/HttpContextExtensionsTests.cs
test/Microsoft.AspNetCore.OData.Tests/Formatter/ODataActionParametersTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.bsl

1. Fixes #1487 : Minimal API TimeZoneInfo for Serialization in minimal APi
2. Enable ODataActionParameter and ODataUntypedActionParameter binding

Fixes #1487 : Minimal API TimeZoneInfo for Serialization

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson/Microsoft.AspNetCore.OData.NewtonsoftJson.csproj
tool/builder.versions.settings.targets

*This pull request fixes #xxx.*
`Newtonsoft.Json` prior to version 13.0.1 is vulnerable to Insecure Defaults due to improper handling of expressions with high nesting level that lead to StackOverFlow exception or high CPU and RAM usage.
This PR handles this security vulnerabilities by updating affected dependencies:
- [CVE-2024-21907](https://github.com/advisories/GHSA-5crp-9r3c-p9vr)
*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

Fix vulnerable dependencies in newtonsoft.json
