OData/AspNetCoreOData

test/Microsoft.AspNetCore.OData.E2E.Tests/Extensions/HttpContentExtensions.cs

Test automated build trigger - Take 2

Test automated build trigger - Take 2

---

sample/ODataSampleCommon/ODataEndpointController.cs
src/Microsoft.AspNetCore.OData/ODataApplicationBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Routing/ODataRouteDebugMiddleware.cs

small changes to HTML template in the OData route controller

OData route Debug controller formatting

---

docs/routing.md

Fix capitalization for consistency between two comma separated statements.

Update routing.md doc

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
src/Microsoft.AspNetCore.OData/Query/ParameterAliasNodeTranslator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/FilterBinderTests.cs

Add support for the following:
$filter=navProp/$count gt 10
$filter=navProp/$count($filter=prop gt 1) gt 2
$filter=collectionValuedProp/$count gt 10
$filter=collectionValuedProp/$count($filter=prop gt 1) gt 2

Add support for dollar count segment in filter

---

src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs

Fix incorrect GetProperties method logic (based on https://github.com/OData/WebApi/issues/2516)

AmbiguousMatchException for properties with new modifier (Again)

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Routing/Conventions/ActionRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/EntitySetRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/FunctionRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/NavigationRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/OperationRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/PropertyRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/RefRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Conventions/SingletonRoutingConvention.cs
src/Microsoft.AspNetCore.OData/Routing/Template/ActionImportSegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/ActionSegmentTemplate.cs
src/Microsoft.AspNetCore.OData/Routing/Template/FunctionSegmentTemplate.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net5.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/ActionRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/EntitySetRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/FunctionRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/NavigationRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/PropertyRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/RefRoutingConventionTests.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/SingletonRoutingConventionTests.cs

Routing conventions code improvements

Routing conventions code improvements

---

src/Microsoft.AspNetCore.OData/Query/Expressions/FilterBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Expressions/SelectExpandBinderTest.cs

Fix #233 
Code lifted from this commit https://github.com/OData/WebApi/commit/0e7a74fdec50a04ea7c497ad8982989df1e60f31

 Fix bug in Filter Any within Expand

---

src/Microsoft.AspNetCore.OData/Batch/ODataBatchMiddleware.cs
test/Microsoft.AspNetCore.OData.Tests/Batch/DefaultODataBatchHandlerTest.cs
test/Microsoft.AspNetCore.OData.Tests/Batch/ODataBatchMiddlewareTest.cs

Reverts OData/AspNetCoreOData#187
Some changes to how the edm model is accessible broke the fix. Reverting so I can fix this in a new pr.

Revert "Fix behaviour for Preflight requests on the ODataBatchMiddleware"

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml

This diff should have been commit in this PR #306

Add missing changes to Microsoft.AspNetCore.OData.xml

---

sample/ODataNewtonsoftJsonSample/Startup.cs

Also set max top, so $top can be used.

Permit Count, to prevent exception when using ..../$count. 

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/OrderByQueryOptionTest.cs

Remove the HandleNullPropagationOption in GetQuerySetting

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson.Nightly.nuspec
src/Microsoft.AspNetCore.OData.NewtonsoftJson.Release.nuspec
src/Microsoft.AspNetCore.OData.NewtonsoftJson/Microsoft.AspNetCore.OData.NewtonsoftJson.csproj
test/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests/Microsoft.AspNetCore.OData.NewtonsoftJson.Tests.csproj

Add support for net6.0 as a target to address https://github.com/OData/AspNetCoreOData/issues/488

Add support for net6.0 for AspNetCore.OData.NewtonsoftJson

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
tool/builder.versions.settings.targets

- Updates ODL version to 7.12.2
- Updates release version to 8.0.11

Update release version to 8.0.11 and referenced ODL to 7.12.2

---

src/Microsoft.AspNetCore.OData/Query/Validator/ComputeQueryValidator.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/ComputeQueryValidatorTests.cs

issue #730. 
Update the Compute query validator to let ODL verify the compute clause.

Verify the compute clause in compute query validator

---

sample/ODataRoutingSample/Controllers/v1/CustomersController.cs
sample/ODataRoutingSample/Models/Customer.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinderContext.cs

fix issue #420: problem with  $apply and $orderby

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/ODataOptions.cs
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.Tests/ODataOptionsTests.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Enable customer to setup ODataVersion when config route component

---

src/Microsoft.AspNetCore.OData/Abstracts/ContainerBuilderExtensions.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/FilterValidatorContext.cs
src/Microsoft.AspNetCore.OData/Query/Validator/QueryValidatorContext.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/FilterQueryValidatorTests.cs

Fixes #819
Refactor FilterQueryValidator to make it thread safe.

Refactor FilterQueryValidator to make it thread safe

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataResourceSerializer.cs

fix: Pass QueryContext to nestedWriteContext #758

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/Expressions/SelectExpandBinder.cs
src/Microsoft.AspNetCore.OData/Query/ODataQueryOptions.cs
src/Microsoft.AspNetCore.OData/Query/ODataQuerySettings.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

fixes #836: Have ability to apply ignore query options on nested query options

---

src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/Query/Query/DefaultSkipTokenHandler.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ServerSidePaging/ServerSidePagingTests.cs

Fix skiptoken paging edge case where property is nullable on CLR type but not nullable on Edm type

Fix skiptoken paging edge case where property is nullable on CLR type but not nullable on Edm type

---

tool/builder.versions.settings.targets

Update release version to 8.1.1

Update release version to 8.1.1

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Properties/SRResources.Designer.cs
src/Microsoft.AspNetCore.OData/Properties/SRResources.resx
src/Microsoft.AspNetCore.OData/Routing/Conventions/RefRoutingConvention.cs
test/Microsoft.AspNetCore.OData.Tests/Routing/Conventions/RefRoutingConventionTests.cs

fix: Matching property names based on ignoring case

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
tool/builder.versions.settings.targets

update ODL version to 7.16.0
update release version to 8.2.0

update ODL version to 7.16.0

---

src/Microsoft.AspNetCore.OData/Query/Expressions/BinderExtensions.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

This PR fixes this issue: https://github.com/OData/AspNetCoreOData/issues/939
This PR https://github.com/OData/AspNetCoreOData/pull/919 fixes $apply combined with groupby and $orderby.

fix $apply with groupby with $filter

---

src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinderContext.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

This PR fixes https://github.com/OData/AspNetCoreOData/issues/918

fix $apply without groupby

---

src/Microsoft.AspNetCore.OData/Query/Validator/FilterQueryValidator.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ModelBoundQuerySettings/ModelBoundQuerySettingsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ModelBoundQuerySettings/ModelBoundQuerySettingsDataModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ModelBoundQuerySettings/ModelBoundQuerySettingsDataSource.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ModelBoundQuerySettings/ModelBoundQuerySettingsEdmModel.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ModelBoundQuerySettings/ModelBoundQuerySettingsTests.cs

This pull request ports this https://github.com/OData/WebApi/pull/2790 7.x fix to 8.x

Fix filter in nested collections in model-bound query settings scenario

---

src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/UnboundOperation/UnboundOperationTest.cs

This PR fixes this issue: https://github.com/OData/AspNetCoreOData/issues/725

return bad request for an empty filter

---

src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataSerializerContext.cs
tool/builder.versions.settings.targets

Fixes #1017 
Add the null check to avoiding null reference exception.

Fixes #1017: resolve the null reference exception by adding the null check

---

src/Microsoft.AspNetCore.OData/Formatter/Value/TypedEdmStructuredObject.cs

The `GetPropertyValue` method retrieves the value of a property from an instance object through reflection.
Currently, we generate property getter delegates for each property type and store them in a cache. Subsequently, we invoke these cached delegates to obtain property values. This approach with delegates is more efficient compared to direct reflection. However, the utilization of a cache introduces some overhead. We employ a `ConcurrentDictionary` for caching the property getter delegates. Checking for the existence of a key in the dictionary using TryGetValue appears to be relatively resource-intensive.
I attempted to enhance the performance by replacing the existing logic, which involves creating delegates through reflection, with expressions and dynamic methods, including the use …

Perf Fix : GetPropertyValue

---

sample/BenchmarkServer/Controllers/ProductsController.cs
sample/BenchmarkServer/EdmModelBuilder.cs
sample/BenchmarkServer/Models/Product.cs

I've added the following to the server benchmark project: 
1. A collection property
2. An action and a function
3. A dynamic property
4. A concurrency property.

Add collection property, action, function and dynamic properties to benchmark server project. 

---

src/Microsoft.AspNetCore.OData/Deltas/DeltaDeletedResourceOfT.cs
src/Microsoft.AspNetCore.OData/Deltas/DeltaOfT.cs
src/Microsoft.AspNetCore.OData/Formatter/Deserialization/ODataResourceDeserializer.cs
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
test/Microsoft.AspNetCore.OData.E2E.Tests/ComplexTypeInheritance/ComplexTypeInheritanceControllers.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/ComplexTypeInheritance/ComplexTypeInheritanceTests.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/OpenType/AccountsController.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/OpenType/TypedOpenTypeTest.cs
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.Net6.bsl
test/Microsoft.AspNetCore.OData.Tests/PublicApi/Microsoft.AspNetCore.OData.PublicApi.NetCore31.bsl

Fixes #591 
Porting https://github.com/OData/WebApi/pull/2575 and https://github.com/OData/WebApi/pull/2601

PATCH derived complex types

---

src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs

Fixes #1177: Ensure that elementType is not null when calling elementType.IsUntyped()

---

tool/builder.versions.settings.targets

Update version to 8.2.5

---

src/Microsoft.AspNetCore.OData/Query/EnableQueryAttribute.cs

Fix ODaya typo

---

src/Microsoft.AspNetCore.OData/Common/TypeHelper.cs
src/Microsoft.AspNetCore.OData/Edm/DefaultODataTypeMapper.cs
src/Microsoft.AspNetCore.OData/Edm/EdmPrimitiveHelper.cs
src/Microsoft.AspNetCore.OData/Formatter/Serialization/ODataPrimitiveSerializer.cs
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/Query/ClrCanonicalFunctions.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/ExpressionBinderHelper.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.SingleValueFunctionCall.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/QueryBinder.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/DateOnlyTimeOnly/DateAndTimeOfDayWithEfTest.cs
test/Microsoft.AspNetCore.OData.E2E.Tests/EntitySetAggregation/EntitySetAggregationTests.cs

Fixes https://github.com/OData/AspNetCoreOData/issues/1294

feat: adding support for frameworks greater than and equal to NET6

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
tool/builder.versions.settings.targets

- Update ODL to 7.21.6
- Bump AspNetCore.OData version to 8.2.6

Update ODL to 7.21.6 and bump version to 8.2.6

---

tool/builder.versions.settings.targets

- Update ODataLibPackageDependency version to [7.21.6, 8.0.0)

Update ODataLibPackageDependency to [7.21.6, 8.0.0)

---

sample/ODataRoutingSample/ODataRoutingSample.csproj
src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.csproj
tool/builder.versions.settings.targets

- Update ODL to 8.2.2
- Bump AspNetCore.OData version to 9.1.1

Update ODL version to 8.2.2 and Bump AspNetCore.OData to 9.1.1

---

src/Microsoft.AspNetCore.OData/Routing/ODataPathExtensions.cs
test/Microsoft.AspNetCore.OData.Tests/ODataPathExtensionsTests.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Query/ODataQueryOptionTests.cs

Fixes #1379: Enable to validate query option on unbound functions

Fixes #1379: Enable to validate query option on unbound functions

---

pipelines/azure_pipelines.yml
tool/ValidateODataPackageVersions.ps1

Cherry-pick https://github.com/OData/AspNetCoreOData/commit/275985bec343a8546b4134ac776e47cecb03153f

Port to 8.x: Validate ODL Version in csproj against builder.versions.settings.targets

---

pipelines/azure_pipelines_nightly.yml

Migrate to ESRP v5

---

pipelines/azure_pipelines_nightly.yml

Migrate 8.x to ESRP v5

---

src/Microsoft.AspNetCore.OData/PublicAPI.Shipped.txt
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
tool/builder.versions.settings.targets

Bump version to 9.2.1

---

src/Microsoft.AspNetCore.OData/Microsoft.AspNetCore.OData.xml
src/Microsoft.AspNetCore.OData/PublicAPI.Unshipped.txt
src/Microsoft.AspNetCore.OData/Query/ODataQueryContextExtensions.cs
src/Microsoft.AspNetCore.OData/Query/Query/SearchQueryOption.cs
src/Microsoft.AspNetCore.OData/Query/Validator/Interfaces/ISearchQueryValidator.cs
src/Microsoft.AspNetCore.OData/Query/Validator/ODataQueryValidator.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/SearchQueryValidatorTest.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/ValidationTestHelper.cs

Fixes #1455: Add ISearchQueryValidator
Enable to provide validations on the Search query options.

Fixes #1455 Add ISearchQueryValidator

---

src/Microsoft.AspNetCore.OData/Query/Expressions/AggregationFlatteningResult.cs
src/Microsoft.AspNetCore.OData/Query/Expressions/IComputeBinder.cs
test/Microsoft.AspNetCore.OData.Tests/Query/Validator/ODataQueryValidatorTests.cs

Fix/add copyright info and minor type and method documentation refactor

Add missing copyright info and minor type and method documentation refactor

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson.Nightly.nuspec
src/Microsoft.AspNetCore.OData.NewtonsoftJson.Release.nuspec
src/Microsoft.AspNetCore.OData.Nightly.nuspec
src/Microsoft.AspNetCore.OData.Release.nuspec

Troubleshooting the following error when pushing nuget package:
> Response status code does not indicate success: 400 (The package is not compliant with metadata requirements for Microsoft packages on NuGet.org. Go to https://aka.ms/Microsoft-NuGet-Compliance for more information. Policy violations: The package metadata defines 'OData (.NET Foundation)' as one of the authors which is not allowed by policy. The package metadata contains a non-compliant copyright element.).

Fix authors metadata

---

src/Microsoft.AspNetCore.OData.NewtonsoftJson.Nightly.nuspec
src/Microsoft.AspNetCore.OData.NewtonsoftJson.Release.nuspec
src/Microsoft.AspNetCore.OData.Nightly.nuspec
src/Microsoft.AspNetCore.OData.Release.nuspec

Match author and copyright metadata to signing certificate to mitigate issue blocking publishing to Nuget

Match author and copyright metadata to signing certificate

---

README.md

Fix: #1519
This is to update the readme:
- Update sample code
- Provide links to the sample codes

Update README to add compiled code
